-- ============================================================================
-- 0001 — phase14_dynamic_systems (Phase 14)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 14.1 Event Ledger. Append-only. Nothing is ever UPDATEd or DELETEd here:
-- retiring a belief is a transition, not a delete. This is NOT audit_events
-- (which stays exactly as it was); the ledger sits alongside it.
CREATE TABLE IF NOT EXISTS knowledge_events (
  id                TEXT PRIMARY KEY,
  seq               BIGSERIAL,
  ts_ms             BIGINT NOT NULL,
  occurred_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  workspace_id      TEXT,
  entity_type       TEXT NOT NULL,
  entity_id         TEXT NOT NULL,
  transition        TEXT NOT NULL,
  from_state        JSONB,
  to_state          JSONB,
  delta             JSONB,
  source_kind       TEXT,
  source_message_id TEXT,
  source_run_id     TEXT,
  reversible        BOOLEAN NOT NULL DEFAULT TRUE,
  payload           JSONB,
  created_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS knowledge_events_seq_idx ON knowledge_events (seq);
CREATE INDEX IF NOT EXISTS knowledge_events_entity_idx ON knowledge_events (entity_type, entity_id, ts_ms);
CREATE INDEX IF NOT EXISTS knowledge_events_run_idx ON knowledge_events (source_run_id);
CREATE INDEX IF NOT EXISTS knowledge_events_transition_idx ON knowledge_events (transition, occurred_at DESC);
CREATE INDEX IF NOT EXISTS knowledge_events_ws_time_idx ON knowledge_events (workspace_id, ts_ms DESC);

-- 14.2/14.3 Beliefs: current state, maintained transactionally for fast reads.
-- The authoritative history lives in knowledge_events; this row is the fold's
-- materialized head, and replay() can reconstruct it at any past millisecond.
CREATE TABLE IF NOT EXISTS beliefs (
  id                 TEXT PRIMARY KEY,
  workspace_id       TEXT NOT NULL,
  statement          TEXT NOT NULL,
  statement_key      TEXT NOT NULL,
  status             TEXT NOT NULL DEFAULT 'active',
  hypothesis         BOOLEAN NOT NULL DEFAULT FALSE,
  confidence         NUMERIC NOT NULL DEFAULT 0.5,
  evidence_level     TEXT DEFAULT 'inferred',
  volatility         TEXT DEFAULT 'medium',
  source_memory_id   TEXT,
  support_count      INTEGER NOT NULL DEFAULT 1,
  contradict_count   INTEGER NOT NULL DEFAULT 0,
  first_seen_ms      BIGINT NOT NULL,
  last_confirmed_ms  BIGINT NOT NULL,
  retired_at_ms      BIGINT,
  successor_id       TEXT,
  lineage            JSONB,
  created_date       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS beliefs_ws_key_idx ON beliefs (workspace_id, statement_key);
CREATE INDEX IF NOT EXISTS beliefs_ws_status_idx ON beliefs (workspace_id, status, confidence DESC);

-- 14.3 Confidence history: one row per confidence change, for any entity that
-- carries confidence (beliefs, memories, relationships).
CREATE TABLE IF NOT EXISTS confidence_history (
  id              TEXT PRIMARY KEY,
  entity_type     TEXT NOT NULL,
  entity_id       TEXT NOT NULL,
  confidence      NUMERIC NOT NULL,
  prev_confidence NUMERIC,
  delta           NUMERIC,
  source_event_id TEXT,
  source_run_id   TEXT,
  ts_ms           BIGINT NOT NULL,
  created_date    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS confidence_history_entity_idx ON confidence_history (entity_type, entity_id, ts_ms);

-- 14.4 Relationship Dynamics: living structures with strength and direction.
-- strength is materialized as of strength_as_of_ms; the effective strength at
-- any later instant is strength * exp(-ln2 * age / half_life), so stale links
-- weaken on their own without a writer having to touch them.
CREATE TABLE IF NOT EXISTS relationships (
  id                  TEXT PRIMARY KEY,
  workspace_id        TEXT NOT NULL,
  subject_type        TEXT NOT NULL,
  subject_id          TEXT NOT NULL,
  object_type         TEXT NOT NULL,
  object_id           TEXT NOT NULL,
  kind                TEXT NOT NULL DEFAULT 'association',
  direction           TEXT NOT NULL DEFAULT 'bidirectional',
  strength            NUMERIC NOT NULL DEFAULT 0.5,
  strength_as_of_ms   BIGINT NOT NULL,
  interactions        INTEGER NOT NULL DEFAULT 1,
  status              TEXT NOT NULL DEFAULT 'active',
  merged_into         TEXT,
  split_into          JSONB,
  decay_half_life_ms  BIGINT,
  lineage             JSONB,
  created_date        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS relationships_pair_idx
  ON relationships (workspace_id, kind, subject_type, subject_id, object_type, object_id);
CREATE INDEX IF NOT EXISTS relationships_ws_idx ON relationships (workspace_id, status, strength DESC);

-- 14.5 Coherence Monitor reports: one per council cycle that checked. A
-- contradiction is a measurement, not an error, so it is stored as data.
CREATE TABLE IF NOT EXISTS coherence_reports (
  id               TEXT PRIMARY KEY,
  run_id           TEXT NOT NULL,
  workspace_id     TEXT,
  conversation_id  TEXT,
  message_id       TEXT,
  checked          BOOLEAN NOT NULL DEFAULT FALSE,
  verdict          TEXT NOT NULL DEFAULT 'unchecked',
  draft_shipped    BOOLEAN,
  persisted        BOOLEAN NOT NULL DEFAULT FALSE,
  skip_reason      TEXT,
  claims           JSONB,
  contradictions   JSONB,
  confirmations    JSONB,
  belief_ids       JSONB,
  confidence_delta NUMERIC,
  model_used       TEXT,
  latency_ms       INTEGER,
  note             TEXT,
  created_date     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS coherence_reports_run_idx ON coherence_reports (run_id);
CREATE INDEX IF NOT EXISTS coherence_reports_verdict_idx ON coherence_reports (verdict, created_date DESC);

-- 14.3 ADDITIVE: memory rows carry a confidence and the instant it was set.
-- Existing rows get NULL confidence (unknown) and keep every other value.
ALTER TABLE memories ADD COLUMN IF NOT EXISTS confidence NUMERIC;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS confidence_as_of_ms BIGINT;
