-- ============================================================================
-- 0002 — phase15_metacognition (Phase 15)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 15.1 Reasoning telemetry: exactly one record per orchestration run.
CREATE TABLE IF NOT EXISTS telemetry_runs (
  id                     TEXT PRIMARY KEY,
  workspace_id           TEXT,
  conversation_id        TEXT,
  message_id             TEXT,
  strategy_id            TEXT NOT NULL,
  status                 TEXT NOT NULL,
  started_ms             BIGINT NOT NULL,
  ended_ms               BIGINT,
  latency_ms             INTEGER,
  time_to_first_token_ms INTEGER,
  stages                 JSONB NOT NULL,
  stage_order            JSONB,
  models                 JSONB,
  model_calls            INTEGER NOT NULL DEFAULT 0,
  tokens_prompt          INTEGER NOT NULL DEFAULT 0,
  tokens_completion      INTEGER NOT NULL DEFAULT 0,
  tokens_total           INTEGER NOT NULL DEFAULT 0,
  tokens_measured        BOOLEAN NOT NULL DEFAULT FALSE,
  tokens_estimated       INTEGER NOT NULL DEFAULT 0,
  cost_usd               NUMERIC,
  cost_rate_known        BOOLEAN NOT NULL DEFAULT FALSE,
  confidence             NUMERIC,
  confidence_source      TEXT,
  coherence_verdict      TEXT,
  coherence_contradictions INTEGER NOT NULL DEFAULT 0,
  vetoed                 BOOLEAN NOT NULL DEFAULT FALSE,
  veto_flags             JSONB,
  veto_reason            TEXT,
  veto_draft_origin      TEXT,
  veto_draft_sha256      TEXT,
  retries                INTEGER NOT NULL DEFAULT 0,
  failures               JSONB,
  failure_count          INTEGER NOT NULL DEFAULT 0,
  adaptive               JSONB,
  ledger_events          INTEGER NOT NULL DEFAULT 0,
  knowledge              JSONB,
  task_type              TEXT,
  complexity             TEXT,
  response_chars         INTEGER,
  error_message          TEXT,
  created_date           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS telemetry_runs_created_idx ON telemetry_runs (created_date DESC);
CREATE INDEX IF NOT EXISTS telemetry_runs_conv_idx ON telemetry_runs (conversation_id, created_date DESC);
CREATE INDEX IF NOT EXISTS telemetry_runs_status_idx ON telemetry_runs (status, created_date DESC);

-- 15.1 Per model call, including every failure the layer can see: timeouts,
-- aborts, upstream HTTP errors, malformed JSON. One row per callLLM().
CREATE TABLE IF NOT EXISTS telemetry_model_calls (
  id                TEXT PRIMARY KEY,
  run_id            TEXT NOT NULL,
  seq               INTEGER NOT NULL DEFAULT 1,
  stage             TEXT,
  purpose           TEXT,
  model             TEXT,
  requested_model   TEXT,
  status            TEXT NOT NULL,
  http_status       INTEGER,
  latency_ms        INTEGER,
  streamed          BOOLEAN NOT NULL DEFAULT FALSE,
  tokens_prompt     INTEGER,
  tokens_completion INTEGER,
  tokens_total      INTEGER,
  tokens_measured   BOOLEAN NOT NULL DEFAULT FALSE,
  chars_out         INTEGER,
  cost_usd          NUMERIC,
  error_class       TEXT,
  error_message     TEXT,
  attempt           INTEGER NOT NULL DEFAULT 1,
  created_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS telemetry_model_calls_run_idx ON telemetry_model_calls (run_id, seq);
CREATE INDEX IF NOT EXISTS telemetry_model_calls_status_idx ON telemetry_model_calls (status, created_date DESC);

-- 15.2 Strategy registry. server/shared/registry.js was checked first and does
-- NOT fit this role: it is a per-run in-process map of stage name -> agent
-- (createRegistry() is called inside runCouncilTurn and thrown away), it holds
-- no selection signals, no persistence and no enable/disable state. This table
-- is the durable registry. Seeded with exactly one row: the canonical pipeline.
CREATE TABLE IF NOT EXISTS strategies (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  description       TEXT,
  selection_signals JSONB NOT NULL,
  enabled           BOOLEAN NOT NULL DEFAULT TRUE,
  is_default        BOOLEAN NOT NULL DEFAULT FALSE,
  evidence          JSONB,
  policy_ref        TEXT,
  created_date      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS strategies_name_idx ON strategies (name);

-- 15.3 Evaluation harness results (offline, operator-invoked).
CREATE TABLE IF NOT EXISTS strategy_evaluations (
  id                TEXT PRIMARY KEY,
  evaluation_id     TEXT NOT NULL,
  strategy_id       TEXT NOT NULL,
  arm               TEXT NOT NULL,
  prompt            TEXT NOT NULL,
  trial             INTEGER NOT NULL,
  run_id            TEXT,
  latency_ms        INTEGER,
  cost_usd          NUMERIC,
  vetoed            BOOLEAN,
  coherence_verdict TEXT,
  status            TEXT,
  score             NUMERIC,
  detail            JSONB,
  created_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS strategy_evaluations_eval_idx ON strategy_evaluations (evaluation_id, arm, trial);

-- 15.4 Adaptive orchestrator decisions. Observe mode only in v1: switched is
-- always FALSE and the row records what WOULD have been selected, and why.
CREATE TABLE IF NOT EXISTS adaptive_decisions (
  id                     TEXT PRIMARY KEY,
  run_id                 TEXT NOT NULL,
  mode                   TEXT NOT NULL DEFAULT 'observe',
  selected_strategy_id   TEXT NOT NULL,
  would_select_id        TEXT NOT NULL,
  reason                 TEXT NOT NULL,
  signals                JSONB NOT NULL,
  switched               BOOLEAN NOT NULL DEFAULT FALSE,
  switch_blocked_by      TEXT,
  evidence               JSONB,
  created_date           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS adaptive_decisions_run_idx ON adaptive_decisions (run_id);
CREATE INDEX IF NOT EXISTS adaptive_decisions_created_idx ON adaptive_decisions (created_date DESC);

-- 15.6 Improvement Ledger: append-only record of architectural change
-- proposals, the law that constrains each one, the justification, and whether
-- it was applied or reverted. Refusals are rows too.
CREATE TABLE IF NOT EXISTS improvement_ledger (
  id            TEXT PRIMARY KEY,
  seq           BIGSERIAL,
  ts_ms         BIGINT NOT NULL,
  action        TEXT NOT NULL,
  target        TEXT,
  proposal      JSONB NOT NULL,
  evidence      JSONB,
  law_refs      JSONB,
  justification TEXT,
  decision      TEXT NOT NULL,
  reasons       JSONB,
  applied       BOOLEAN NOT NULL DEFAULT FALSE,
  reverted      BOOLEAN NOT NULL DEFAULT FALSE,
  revert_of     TEXT,
  proposed_by   TEXT,
  created_date  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS improvement_ledger_seq_idx ON improvement_ledger (seq);
CREATE INDEX IF NOT EXISTS improvement_ledger_decision_idx ON improvement_ledger (decision, ts_ms DESC);
CREATE INDEX IF NOT EXISTS improvement_ledger_action_idx ON improvement_ledger (action, ts_ms DESC);
