-- ============================================================================
-- 0003 — phase16_latency_observability (Phase 16)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
ALTER TABLE telemetry_runs ADD COLUMN IF NOT EXISTS performance JSONB;

ALTER TABLE telemetry_model_calls ADD COLUMN IF NOT EXISTS request_id TEXT;
ALTER TABLE telemetry_model_calls ADD COLUMN IF NOT EXISTS response_headers_ms INTEGER;
ALTER TABLE telemetry_model_calls ADD COLUMN IF NOT EXISTS response_decode_ms INTEGER;
ALTER TABLE telemetry_model_calls ADD COLUMN IF NOT EXISTS prompt_cached_tokens INTEGER;
ALTER TABLE telemetry_model_calls ADD COLUMN IF NOT EXISTS requested_service_tier TEXT;
ALTER TABLE telemetry_model_calls ADD COLUMN IF NOT EXISTS service_tier TEXT;
