-- ============================================================================
-- 0004 — phase17_sources_and_agents (Phase 17)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
CREATE TABLE IF NOT EXISTS sources (
  id                 TEXT PRIMARY KEY,
  workspace_id       TEXT NOT NULL,
  conversation_id    TEXT,
  kind               TEXT NOT NULL,
  name               TEXT NOT NULL,
  canonical_url      TEXT,
  final_url          TEXT,
  media_type         TEXT NOT NULL,
  byte_size          INTEGER NOT NULL,
  content_sha256     TEXT NOT NULL,
  extracted_text     TEXT NOT NULL,
  extraction         JSONB NOT NULL,
  risk_flags         JSONB NOT NULL,
  fetched_at         TIMESTAMPTZ,
  created_date       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sources_workspace_created_idx ON sources (workspace_id, created_date DESC);
CREATE INDEX IF NOT EXISTS sources_conversation_idx ON sources (conversation_id, created_date DESC);
CREATE INDEX IF NOT EXISTS sources_sha_idx ON sources (workspace_id, content_sha256);
CREATE UNIQUE INDEX IF NOT EXISTS sources_workspace_kind_sha_unique_idx ON sources (workspace_id, kind, content_sha256, COALESCE(canonical_url, ''));
CREATE INDEX IF NOT EXISTS sources_url_idx ON sources (workspace_id, canonical_url);

CREATE TABLE IF NOT EXISTS source_chunks (
  id                 TEXT PRIMARY KEY,
  source_id          TEXT NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
  ordinal            INTEGER NOT NULL,
  locator            JSONB NOT NULL,
  content            TEXT NOT NULL,
  content_sha256     TEXT NOT NULL,
  char_start         INTEGER NOT NULL,
  char_end           INTEGER NOT NULL,
  created_date       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS source_chunks_ordinal_idx ON source_chunks (source_id, ordinal);
CREATE INDEX IF NOT EXISTS source_chunks_source_idx ON source_chunks (source_id, ordinal);

CREATE TABLE IF NOT EXISTS agent_runs (
  id                 TEXT PRIMARY KEY,
  council_run_id     TEXT,
  workspace_id       TEXT NOT NULL,
  conversation_id    TEXT,
  objective          TEXT NOT NULL,
  mode               TEXT NOT NULL,
  status             TEXT NOT NULL,
  budget             JSONB NOT NULL,
  plan               JSONB NOT NULL,
  summary            JSONB,
  started_ms         BIGINT NOT NULL,
  ended_ms           BIGINT,
  error_message      TEXT,
  created_date       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS agent_runs_council_run_idx ON agent_runs (council_run_id);
CREATE INDEX IF NOT EXISTS agent_runs_workspace_idx ON agent_runs (workspace_id, created_date DESC);

CREATE TABLE IF NOT EXISTS agent_steps (
  id                 TEXT PRIMARY KEY,
  agent_run_id       TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE RESTRICT,
  ordinal            INTEGER NOT NULL,
  tool_name          TEXT NOT NULL,
  risk_level         TEXT NOT NULL,
  requires_approval  BOOLEAN NOT NULL DEFAULT FALSE,
  status             TEXT NOT NULL,
  input              JSONB NOT NULL,
  output             JSONB,
  error_message      TEXT,
  idempotency_key    TEXT NOT NULL,
  started_ms         BIGINT,
  ended_ms           BIGINT,
  created_date       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS agent_steps_ordinal_idx ON agent_steps (agent_run_id, ordinal);
CREATE UNIQUE INDEX IF NOT EXISTS agent_steps_idempotency_idx ON agent_steps (idempotency_key);

CREATE TABLE IF NOT EXISTS agent_events (
  id                 TEXT PRIMARY KEY,
  seq                BIGSERIAL,
  agent_run_id       TEXT NOT NULL,
  step_id            TEXT,
  event_type         TEXT NOT NULL,
  from_status        TEXT,
  to_status          TEXT,
  detail             JSONB,
  ts_ms              BIGINT NOT NULL,
  created_date       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS agent_events_seq_idx ON agent_events (seq);
CREATE INDEX IF NOT EXISTS agent_events_run_idx ON agent_events (agent_run_id, seq);

CREATE TABLE IF NOT EXISTS agent_approvals (
  id                 TEXT PRIMARY KEY,
  agent_run_id       TEXT NOT NULL,
  step_id            TEXT NOT NULL,
  decision           TEXT NOT NULL,
  scope_sha256       TEXT NOT NULL,
  reason             TEXT,
  decided_ms         BIGINT NOT NULL,
  created_date       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS agent_approvals_step_idx ON agent_approvals (step_id, decided_ms DESC);
