-- ============================================================================
-- 0005 — phase18_research_projects_images (Phase 18)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 18.1 Durable projects. A project groups conversations, immutable evidence,
-- agent runs, and research decisions around one investigation. It is a folder,
-- not an account boundary: the app stays single-workspace and single-tenant.
CREATE TABLE IF NOT EXISTS projects (
  id           TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  name         TEXT NOT NULL,
  objective    TEXT,
  created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS projects_workspace_idx ON projects (workspace_id, updated_date DESC);

-- 18.1 Conversations and sources become optionally project-scoped. Existing
-- rows stay NULL (ungrouped) and keep every previous meaning. Deleting a
-- project detaches, never deletes, its conversations and sources.
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS project_id TEXT;
CREATE INDEX IF NOT EXISTS conversations_project_idx ON conversations (project_id, updated_date DESC);

ALTER TABLE sources ADD COLUMN IF NOT EXISTS project_id TEXT;
CREATE INDEX IF NOT EXISTS sources_project_idx ON sources (project_id, created_date DESC);

-- 18.2 Immutable image originals. The bytes are stored once, keyed 1:1 to the
-- hashed source row; nothing here is ever UPDATEd or DELETEd by an accessor.
CREATE TABLE IF NOT EXISTS source_images (
  id             TEXT PRIMARY KEY,
  source_id      TEXT NOT NULL UNIQUE REFERENCES sources(id) ON DELETE RESTRICT,
  format         TEXT NOT NULL,
  width          INTEGER NOT NULL,
  height         INTEGER NOT NULL,
  byte_size      INTEGER NOT NULL,
  content_sha256 TEXT NOT NULL,
  bytes          BYTEA NOT NULL,
  created_date   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS source_images_sha_idx ON source_images (content_sha256);

-- 18.3 Vision-analysis provenance: one row per model reading of an immutable
-- image original. A reading is a recorded interpretation, not the artifact:
-- the artifact is the hashed bytea above, and the reading is labeled as such
-- in evidence packs. Rows are append-only; a re-analysis is a new row.
CREATE TABLE IF NOT EXISTS image_analyses (
  id            TEXT PRIMARY KEY,
  source_id     TEXT NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
  model_used    TEXT NOT NULL,
  status        TEXT NOT NULL,
  visual_type   TEXT,
  summary       TEXT,
  regions       JSONB NOT NULL DEFAULT '[]'::jsonb,
  latency_ms    INTEGER,
  attempts      INTEGER NOT NULL DEFAULT 1,
  usage         JSONB,
  error_message TEXT,
  created_date  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS image_analyses_source_idx ON image_analyses (source_id, created_date DESC);
