-- ============================================================================
-- 0007 — phase20_subagents_promotion (Phase 20)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
CREATE TABLE IF NOT EXISTS goal_subagents (
  id                    TEXT PRIMARY KEY,
  workspace_id          TEXT NOT NULL,
  goal_id               TEXT NOT NULL REFERENCES autonomy_goals(id) ON DELETE RESTRICT,
  agent_id              TEXT,
  tick_id               TEXT,
  parent_step_id        TEXT,
  objective             TEXT NOT NULL,
  skills                JSONB NOT NULL DEFAULT '[]'::jsonb,
  budget                JSONB NOT NULL DEFAULT '{}'::jsonb,
  spent                 JSONB NOT NULL DEFAULT '{}'::jsonb,
  status                TEXT NOT NULL,
  output                JSONB,
  error_message         TEXT,
  started_ms            BIGINT,
  ended_ms              BIGINT,
  created_date          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS goal_subagents_goal_idx ON goal_subagents (goal_id, created_date DESC);

CREATE TABLE IF NOT EXISTS note_promotions (
  id                    TEXT PRIMARY KEY,
  workspace_id          TEXT NOT NULL,
  goal_id               TEXT NOT NULL,
  agent_id              TEXT,
  note_id               TEXT NOT NULL,
  target                TEXT NOT NULL,
  status                TEXT NOT NULL,
  reason                TEXT,
  decided_ms            BIGINT,
  decision_source       TEXT,
  applied_memory_id     TEXT,
  applied_belief_id     TEXT,
  run_id                TEXT,
  message_id            TEXT,
  created_date          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS note_promotions_ws_idx ON note_promotions (workspace_id, status, created_date DESC);
CREATE INDEX IF NOT EXISTS note_promotions_goal_idx ON note_promotions (goal_id, created_date DESC);
CREATE INDEX IF NOT EXISTS note_promotions_note_idx ON note_promotions (note_id, target);
