-- ============================================================================
-- 0008 — phase21_webhook_effects (Phase 21)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
ALTER TABLE autonomy_outbox ADD COLUMN IF NOT EXISTS destination TEXT;
CREATE INDEX IF NOT EXISTS autonomy_outbox_destination_idx
  ON autonomy_outbox (destination, created_date DESC);

CREATE TABLE IF NOT EXISTS autonomy_rung_evidence (
  id                    TEXT PRIMARY KEY,
  workspace_id          TEXT NOT NULL,
  rung                  TEXT NOT NULL,
  tier                  TEXT,
  decision              TEXT NOT NULL,
  gate                  JSONB NOT NULL DEFAULT '{}'::jsonb,
  metrics               JSONB NOT NULL DEFAULT '{}'::jsonb,
  metrics_sha256        TEXT NOT NULL,
  reason                TEXT,
  decided_by            TEXT,
  decided_ms            BIGINT NOT NULL,
  created_date          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS autonomy_rung_evidence_ws_idx
  ON autonomy_rung_evidence (workspace_id, rung, decided_ms DESC);
