-- ============================================================================
-- 0009 — phase22_context_and_structured_memory (Phase 22)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
ALTER TABLE memories ADD COLUMN IF NOT EXISTS memory_layer TEXT NOT NULL DEFAULT 'semantic';
ALTER TABLE memories ADD COLUMN IF NOT EXISTS memory_key TEXT;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS memory_value JSONB;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS memory_schema_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS memories_layer_idx ON memories (workspace_id, memory_layer, is_enabled, importance DESC, created_date DESC);
CREATE INDEX IF NOT EXISTS memories_key_idx ON memories (workspace_id, memory_key);
