-- ============================================================================
-- 0010 — phase23_trust_annotated_graph (Phase 23)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 23.1 Graph nodes: the durable atlas of sessions, sources, intents, people.
CREATE TABLE IF NOT EXISTS graph_nodes (
  id                TEXT PRIMARY KEY,
  workspace_id      TEXT NOT NULL,
  project_id        TEXT,
  conversation_id   TEXT,
  type              TEXT NOT NULL,
  label             TEXT NOT NULL,
  node_key          TEXT NOT NULL,
  content           TEXT NOT NULL,
  content_sha256    TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'active',
  trust             TEXT NOT NULL DEFAULT 'untrusted',
  confidence        NUMERIC NOT NULL DEFAULT 0.5,
  version           INTEGER NOT NULL DEFAULT 1,
  predecessor_id    TEXT,
  successor_id      TEXT,
  provenance        JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_memory_id  TEXT,
  source_message_id TEXT,
  source_run_id     TEXT,
  source_ids        JSONB NOT NULL DEFAULT '[]'::jsonb,
  retired_at_ms     BIGINT,
  created_date      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS graph_nodes_ws_idx ON graph_nodes (workspace_id, status, trust, updated_date DESC);
CREATE INDEX IF NOT EXISTS graph_nodes_type_idx ON graph_nodes (workspace_id, type, status);
CREATE INDEX IF NOT EXISTS graph_nodes_key_idx ON graph_nodes (workspace_id, node_key);
CREATE INDEX IF NOT EXISTS graph_nodes_conv_idx ON graph_nodes (conversation_id, created_date DESC);
CREATE INDEX IF NOT EXISTS graph_nodes_project_idx ON graph_nodes (project_id, created_date DESC);
CREATE INDEX IF NOT EXISTS graph_nodes_pred_idx ON graph_nodes (predecessor_id);
CREATE INDEX IF NOT EXISTS graph_nodes_succ_idx ON graph_nodes (successor_id);
CREATE INDEX IF NOT EXISTS graph_nodes_sha_idx ON graph_nodes (workspace_id, content_sha256);

-- 23.2 Graph edges: provenance-carrying relations between nodes.
CREATE TABLE IF NOT EXISTS graph_edges (
  id                TEXT PRIMARY KEY,
  workspace_id      TEXT NOT NULL,
  src_node_id       TEXT NOT NULL,
  dst_node_id       TEXT NOT NULL,
  kind              TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'active',
  trust             TEXT NOT NULL DEFAULT 'untrusted',
  weight            NUMERIC NOT NULL DEFAULT 0.5,
  version           INTEGER NOT NULL DEFAULT 1,
  predecessor_id    TEXT,
  successor_id      TEXT,
  provenance        JSONB NOT NULL DEFAULT '{}'::jsonb,
  edge_sha256       TEXT NOT NULL,
  source_run_id     TEXT,
  source_message_id TEXT,
  retired_at_ms     BIGINT,
  created_date      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS graph_edges_ws_idx ON graph_edges (workspace_id, kind, status);
CREATE INDEX IF NOT EXISTS graph_edges_src_idx ON graph_edges (src_node_id, status);
CREATE INDEX IF NOT EXISTS graph_edges_dst_idx ON graph_edges (dst_node_id, status);
CREATE INDEX IF NOT EXISTS graph_edges_pair_idx ON graph_edges (workspace_id, kind, src_node_id, dst_node_id);
CREATE INDEX IF NOT EXISTS graph_edges_trust_idx ON graph_edges (workspace_id, trust, status);

-- 23.3 Immutable snapshots: a Merkle root over the sorted node+edge hashes,
-- so "what did the atlas look like when we decided that" stays answerable.
-- Append-only: no accessor UPDATEd or DELETEd these rows.
CREATE TABLE IF NOT EXISTS graph_snapshots (
  id                TEXT PRIMARY KEY,
  workspace_id      TEXT NOT NULL,
  merkle_root       TEXT NOT NULL,
  node_count        INTEGER NOT NULL DEFAULT 0,
  edge_count        INTEGER NOT NULL DEFAULT 0,
  node_ids          JSONB NOT NULL DEFAULT '[]'::jsonb,
  edge_ids          JSONB NOT NULL DEFAULT '[]'::jsonb,
  leaf_hashes       JSONB NOT NULL DEFAULT '[]'::jsonb,
  provenance        JSONB NOT NULL DEFAULT '{}'::jsonb,
  note              TEXT,
  created_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS graph_snapshots_ws_idx ON graph_snapshots (workspace_id, created_date DESC);
CREATE INDEX IF NOT EXISTS graph_snapshots_root_idx ON graph_snapshots (workspace_id, merkle_root);
