-- ============================================================================
-- 0011 — phase24_accounts_and_workspaces (Phase 24)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 24.1 Accounts. Emails are stored normalized (lowercased) and unique.
-- password_hash is nullable: Google-only accounts have none. google_sub is
-- the immutable Google identity; linking an existing account REQUIRES a
-- verified Google email (enforced in server/accounts/service.js).
CREATE TABLE IF NOT EXISTS accounts (
  id             TEXT PRIMARY KEY,
  email          TEXT NOT NULL,
  display_name   TEXT,
  password_hash  TEXT,
  auth_provider  TEXT NOT NULL DEFAULT 'email',
  google_sub     TEXT,
  google_email   TEXT,
  avatar_url     TEXT,
  workspace_id   TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'active',
  last_login_at  TIMESTAMPTZ,
  created_date   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS accounts_email_idx ON accounts (email);
CREATE UNIQUE INDEX IF NOT EXISTS accounts_google_sub_idx ON accounts (google_sub) WHERE google_sub IS NOT NULL;
CREATE INDEX IF NOT EXISTS accounts_workspace_idx ON accounts (workspace_id);

-- 24.2 Groups (brief §2.3). members is the JSON array of user ids; the
-- optional private_writers array carries the "read/write private bucket"
-- flag the role matrix gates on.
CREATE TABLE IF NOT EXISTS account_groups (
  id              TEXT PRIMARY KEY,
  group_name      TEXT NOT NULL,
  owner_id        TEXT NOT NULL,
  members         JSONB NOT NULL DEFAULT '[]'::jsonb,
  private_writers JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_date    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS account_groups_owner_idx ON account_groups (owner_id);

-- 24.3 JWT revocation list. On logout the token's jti lands here until the
-- token's own exp passes (a TTL, Redis-style, in Postgres form).
CREATE TABLE IF NOT EXISTS jwt_blocklist (
  jti          TEXT PRIMARY KEY,
  user_id      TEXT,
  expires_at   TIMESTAMPTZ NOT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS jwt_blocklist_expiry_idx ON jwt_blocklist (expires_at);

-- 24.4 Google OAuth single-use state + nonce (CSRF / replay defence).
CREATE TABLE IF NOT EXISTS google_auth_states (
  state        TEXT PRIMARY KEY,
  nonce        TEXT NOT NULL,
  consumed     BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at   TIMESTAMPTZ NOT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS google_auth_states_expiry_idx ON google_auth_states (expires_at);

-- 24.5 Append-only audit trail (brief §4). One row per mutation or denial:
-- <timestamp, user_id, workspace_id, action, resource_id>. No accessor in the
-- app ever UPDATEs or DELETEs these rows; rotation is a maintenance script.
CREATE TABLE IF NOT EXISTS workspace_audit (
  id           TEXT PRIMARY KEY,
  ts_ms        BIGINT NOT NULL,
  user_id      TEXT,
  workspace_id TEXT,
  action       TEXT NOT NULL,
  resource_id  TEXT,
  detail       JSONB,
  created_date TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS workspace_audit_ws_time_idx ON workspace_audit (workspace_id, ts_ms DESC);
CREATE INDEX IF NOT EXISTS workspace_audit_user_idx ON workspace_audit (user_id, ts_ms DESC);
CREATE INDEX IF NOT EXISTS workspace_audit_action_idx ON workspace_audit (action, ts_ms DESC);
