-- ============================================================================
-- 0014 — phase22c_irreversible_effects (Phase 22)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
CREATE TABLE IF NOT EXISTS effect_approvals (
  id             TEXT PRIMARY KEY,
  workspace_id   TEXT NOT NULL,
  outbox_id      TEXT NOT NULL,
  goal_id        TEXT,
  agent_id       TEXT,
  decision       TEXT NOT NULL,
  scope_sha256   TEXT,
  reason         TEXT,
  decided_by     TEXT,
  decided_ms     BIGINT NOT NULL,
  created_date   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS effect_approvals_outbox_idx
  ON effect_approvals (outbox_id, decided_ms DESC);
CREATE INDEX IF NOT EXISTS effect_approvals_ws_idx
  ON effect_approvals (workspace_id, decided_ms DESC);
