-- ============================================================================
-- 0015 — phase26_council_settings (Phase 26)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
CREATE TABLE IF NOT EXISTS council_settings (
  workspace_id      TEXT PRIMARY KEY,
  governor_enabled  BOOLEAN NOT NULL DEFAULT TRUE,
  critic_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
  source            TEXT NOT NULL DEFAULT 'ui',
  updated_by        TEXT,
  updated_ms        BIGINT NOT NULL,
  created_date      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);
