-- ============================================================================
-- 0018 — phase29_rung_switches (Phase 29)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
ALTER TABLE autonomy_settings ADD COLUMN IF NOT EXISTS rung_residents BOOLEAN;
ALTER TABLE autonomy_settings ADD COLUMN IF NOT EXISTS rung_search BOOLEAN;
ALTER TABLE autonomy_settings ADD COLUMN IF NOT EXISTS rung_external_writes BOOLEAN;
ALTER TABLE autonomy_settings ADD COLUMN IF NOT EXISTS rung_irreversible BOOLEAN;
ALTER TABLE autonomy_settings ADD COLUMN IF NOT EXISTS rung_inbound BOOLEAN;
