-- ============================================================================
-- 0019 — phase30_memory_embeddings (Phase 30)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
ALTER TABLE memories ADD COLUMN IF NOT EXISTS embedding TEXT;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS embedding_model TEXT;
