-- ============================================================================
-- 0021 — phase32_personas (Phase 32)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
CREATE TABLE IF NOT EXISTS personas (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL,
  description    TEXT NOT NULL DEFAULT '',
  prompt_text    TEXT NOT NULL DEFAULT '',
  model_override TEXT,
  temperature    REAL,
  voice          JSONB NOT NULL DEFAULT '{}'::jsonb,
  builtin        INTEGER NOT NULL DEFAULT 0,
  is_active      INTEGER NOT NULL DEFAULT 0,
  created_date   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date   TIMESTAMPTZ NOT NULL DEFAULT now()
);
