-- ============================================================================
-- 0022 — phase33_cleanup_agent (Phase 33)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 33.1 Cleanup proposals: the review queue. One row per finding group;
-- idempotent by (workspace_id, proposal_key). Statuses: requested, approved,
-- applied, refused. Refusals stand; approvals apply synchronously.
CREATE TABLE IF NOT EXISTS cleanup_proposals (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL,
  store         TEXT NOT NULL,
  kind          TEXT NOT NULL,
  title         TEXT NOT NULL,
  detail        JSONB NOT NULL DEFAULT '{}'::jsonb,
  proposal_key  TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'requested',
  reason        TEXT,
  decided_by    TEXT,
  decided_ms    BIGINT,
  applied_ms    BIGINT,
  created_date  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS cleanup_proposals_key_idx
  ON cleanup_proposals (workspace_id, proposal_key);
CREATE INDEX IF NOT EXISTS cleanup_proposals_ws_idx
  ON cleanup_proposals (workspace_id, status, created_date DESC);

-- 33.2 Cleanup runs: one row per audit. The Jeremy-visible log of what the
-- agent found, what it tidied itself, and what it queued for review.
CREATE TABLE IF NOT EXISTS cleanup_runs (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL,
  started_ms    BIGINT NOT NULL,
  finished_ms   BIGINT,
  findings      JSONB NOT NULL DEFAULT '{}'::jsonb,
  tidied        JSONB NOT NULL DEFAULT '{}'::jsonb,
  proposals     JSONB NOT NULL DEFAULT '{}'::jsonb,
  error         TEXT,
  created_date  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS cleanup_runs_ws_idx
  ON cleanup_runs (workspace_id, finished_ms DESC);
