-- ============================================================================
-- 0023 — phase34b_goal_deletion_fk (Phase 34)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 34.1 Goal deletion: a deleted goal's notes must survive as orphans so the
-- cleanup agent's daily audit can propose them to Jeremy's review queue.
-- The original goal_notes.goal_id foreign key was ON DELETE RESTRICT, which
-- would block every deletion of a goal that has notes. Drop the constraint
-- (by lookup, so it works regardless of the auto-generated name); the audit
-- query already anticipates dangling goal_ids.
DO $$
DECLARE cname text;
BEGIN
  SELECT con.conname INTO cname
  FROM pg_constraint con
  JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = ANY(con.conkey)
  WHERE con.conrelid = 'goal_notes'::regclass
    AND con.contype = 'f'
    AND att.attname = 'goal_id'
  LIMIT 1;
  IF cname IS NOT NULL THEN
    EXECUTE 'ALTER TABLE goal_notes DROP CONSTRAINT ' || quote_ident(cname);
  END IF;
END $$;
