-- ============================================================================
-- 0024 — phase35_sapphire_memory_transplant (Phase 35)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 35.1 Edges: the memory graph the priced recall walk traverses.
CREATE TABLE IF NOT EXISTS memory_edges (
  id              TEXT PRIMARY KEY,
  workspace_id    TEXT NOT NULL,
  from_memory_id  TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
  to_memory_id    TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
  edge_type       TEXT NOT NULL DEFAULT 'mentions',
  metadata        JSONB,
  created_by      TEXT,
  created_date    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT memory_edges_no_self_loop CHECK (from_memory_id <> to_memory_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS memory_edges_unique_idx
  ON memory_edges (workspace_id, from_memory_id, to_memory_id, edge_type);
CREATE INDEX IF NOT EXISTS memory_edges_from_idx
  ON memory_edges (workspace_id, from_memory_id);
CREATE INDEX IF NOT EXISTS memory_edges_to_idx
  ON memory_edges (workspace_id, to_memory_id);

-- 35.2 Tending state: day-guards and one-shot announcement flags, per workspace.
CREATE TABLE IF NOT EXISTS memory_tending_state (
  workspace_id        TEXT PRIMARY KEY,
  last_decay_date     TEXT,
  last_librarian_date TEXT,
  decay_announced     BOOLEAN NOT NULL DEFAULT FALSE,
  updated_date        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 35.3 Librarian runs: the nightly journal — one row per round.
CREATE TABLE IF NOT EXISTS librarian_runs (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL,
  started_ms    BIGINT NOT NULL,
  finished_ms   BIGINT,
  passes        JSONB,
  decayed       INTEGER NOT NULL DEFAULT 0,
  error         TEXT,
  created_date  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS librarian_runs_ws_idx
  ON librarian_runs (workspace_id, started_ms DESC);

-- 35.4 One-shot boot markers.
CREATE TABLE IF NOT EXISTS schema_markers (
  key           TEXT PRIMARY KEY,
  value         JSONB,
  created_date  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 35.5 Additive memory columns: favorites, recall instrumentation (never for
-- ranking), librarian processing marks, reversible retirement.
ALTER TABLE memories ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS recall_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS last_recalled TIMESTAMPTZ;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS retired_reason TEXT;
CREATE INDEX IF NOT EXISTS memories_favorite_idx ON memories (workspace_id, is_favorite) WHERE is_favorite;
