-- ============================================================================
-- 0025 — phase36_resident_tools (Phase 36)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 36.1 Tool definitions: Jeremy's hand-typed HTTPS endpoints.
CREATE TABLE IF NOT EXISTS resident_tools (
  id              TEXT PRIMARY KEY,
  workspace_id    TEXT NOT NULL,
  name            TEXT NOT NULL,
  description     TEXT NOT NULL DEFAULT '',
  method          TEXT NOT NULL DEFAULT 'GET',
  url             TEXT NOT NULL,
  headers         JSONB NOT NULL DEFAULT '{}'::jsonb,
  body_template   TEXT NOT NULL DEFAULT '',
  timeout_ms      INTEGER NOT NULL DEFAULT 10000,
  created_by      TEXT,
  created_date    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_date    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT resident_tools_method_check
    CHECK (method IN ('GET','POST','PUT','PATCH','DELETE'))
);
CREATE INDEX IF NOT EXISTS resident_tools_ws_idx
  ON resident_tools (workspace_id, created_date DESC);

-- 36.2 Write-only secrets. The value column is never selected by any list/get
-- accessor; only the executor's resolve path reads it, at send time.
CREATE TABLE IF NOT EXISTS resident_tool_secrets (
  id            TEXT PRIMARY KEY,
  tool_id       TEXT NOT NULL REFERENCES resident_tools(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  value         TEXT NOT NULL,
  created_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT resident_tool_secrets_unique UNIQUE (tool_id, name),
  CONSTRAINT resident_tool_secrets_name_check CHECK (name ~ '^[A-Z0-9_]{1,64}$')
);

-- 36.3 Assignment: which resident may invoke which tool. By slug, so a brief
-- change (a new agent row) does not silently drop the resident's tools.
CREATE TABLE IF NOT EXISTS resident_tool_assignments (
  tool_id       TEXT NOT NULL REFERENCES resident_tools(id) ON DELETE CASCADE,
  agent_slug    TEXT NOT NULL,
  workspace_id  TEXT NOT NULL,
  created_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT resident_tool_assignments_unique UNIQUE (tool_id, agent_slug)
);
CREATE INDEX IF NOT EXISTS resident_tool_assignments_slug_idx
  ON resident_tool_assignments (workspace_id, agent_slug);

-- 36.4 Run history: metadata only. No request/response bodies, no secret
-- values, no query strings (args may carry secrets) -- origin only.
CREATE TABLE IF NOT EXISTS resident_tool_runs (
  id              TEXT PRIMARY KEY,
  workspace_id    TEXT NOT NULL,
  tool_id         TEXT NOT NULL,
  tool_name       TEXT NOT NULL,
  agent_id        TEXT,
  agent_slug      TEXT,
  goal_id         TEXT,
  outbox_id       TEXT,
  method          TEXT NOT NULL,
  url_origin      TEXT NOT NULL,
  status          TEXT NOT NULL,
  status_code     INTEGER,
  latency_ms      INTEGER,
  request_digest  TEXT,
  response_digest TEXT,
  response_chars  INTEGER,
  error           TEXT,
  created_date    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT resident_tool_runs_status_check
    CHECK (status IN ('succeeded','failed','awaiting_approval','refused','staged'))
);
CREATE INDEX IF NOT EXISTS resident_tool_runs_tool_idx
  ON resident_tool_runs (tool_id, created_date DESC);
CREATE INDEX IF NOT EXISTS resident_tool_runs_agent_idx
  ON resident_tool_runs (workspace_id, agent_slug, created_date DESC);
