-- ============================================================================
-- 0027 — phase38_daily_insights (Phase 38)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 38.1 Email configuration, one row per workspace. The password column holds
-- a vault envelope (v1.nonce.tag.ciphertext), never plaintext.
CREATE TABLE IF NOT EXISTS insights_email_config (
  workspace_id      TEXT PRIMARY KEY,
  email_address     TEXT NOT NULL DEFAULT '',
  app_password_enc  TEXT NOT NULL DEFAULT '',
  enabled           BOOLEAN NOT NULL DEFAULT FALSE,
  send_time         TEXT NOT NULL DEFAULT '07:00',
  updated_date      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT insights_email_config_time_check
    CHECK (send_time ~ '^[0-2][0-9]:[0-5][0-9]$')
);

-- 38.2 Digest run journal. Every attempt is recorded — a failed send is
-- visible in Settings, never silent.
CREATE TABLE IF NOT EXISTS insights_digest_runs (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL,
  started_ms    BIGINT NOT NULL,
  finished_ms   BIGINT,
  status        TEXT NOT NULL DEFAULT 'running',
  error         TEXT,
  subject       TEXT,
  preview       TEXT,
  created_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT insights_digest_runs_status_check
    CHECK (status IN ('running','sent','failed','skipped'))
);
CREATE INDEX IF NOT EXISTS insights_digest_runs_ws_idx
  ON insights_digest_runs (workspace_id, started_ms DESC);
