-- ============================================================================
-- 0028 — phase39_email_tools (Phase 39)
-- ============================================================================
-- Generated by scripts/generate-migrations.mjs from server/db/schema.js.
-- Do not edit by hand: edit the source of truth and regenerate.
--
-- ADDITIVE ONLY. This migration creates new tables and indexes and adds
-- columns to existing ones. It never drops, renames, truncates or rewrites
-- existing tables, so existing rows keep their semantics. Every statement is
-- idempotent and safe to re-run.
--
-- Apply with:   node scripts/migrate.mjs
-- (The server also applies these same statements at boot, so running this
--  script is optional — it exists for review and for controlled rollouts.)
-- 39.1 Email tool columns on resident_tools. kind is 'https' (the Phase 36
-- HTTPS endpoint tool) or 'email' (the native Gmail send tool).
ALTER TABLE resident_tools ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'https';
ALTER TABLE resident_tools ADD COLUMN IF NOT EXISTS to_template TEXT NOT NULL DEFAULT '';
ALTER TABLE resident_tools ADD COLUMN IF NOT EXISTS subject_template TEXT NOT NULL DEFAULT '';
